/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KlixCreditBadge {
        "amount": number;
        "b": string;
        "language": string;
    }
}
declare global {
    interface HTMLKlixCreditBadgeElement extends Components.KlixCreditBadge, HTMLStencilElement {
    }
    var HTMLKlixCreditBadgeElement: {
        prototype: HTMLKlixCreditBadgeElement;
        new (): HTMLKlixCreditBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "klix-credit-badge": HTMLKlixCreditBadgeElement;
    }
}
declare namespace LocalJSX {
    interface KlixCreditBadge {
        "amount"?: number;
        "b"?: string;
        "language"?: string;
    }
    interface IntrinsicElements {
        "klix-credit-badge": KlixCreditBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "klix-credit-badge": LocalJSX.KlixCreditBadge & JSXBase.HTMLAttributes<HTMLKlixCreditBadgeElement>;
        }
    }
}
